platform :ios, '8.0'

target "JJLearnIngHelper" do

pod 'Masonry', '~> 0.6.4'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'MLTransition', '~> 2.1.2'
pod 'TPKeyboardAvoiding', '~> 1.2.11'
pod 'MJExtension', '~> 3.0.13'
pod 'AFNetworking', '~> 3.0.4'
pod 'MMDrawerController', '~> 0.6.0'
pod 'SDWebImage', '~> 3.7.2'
end

